language: python
python:
    - 2.7

notifications:
    email: false

env:
# - ANSIBLE_VERSION=devel
  - ANSIBLE_VERSION=v2.3.1.0-1
  - ANSIBLE_VERSION=v2.2.3.0-1

before_install:
  - pip install tox
  - git clone --recursive --depth=1 -b $ANSIBLE_VERSION https://github.com/ansible/ansible
  - pip install ./ansible

script:
    - tox
